# Generated by Django 4.2.2 on 2023-06-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=2000)),
                ('year', models.CharField(max_length=2000)),
                ('length', models.CharField(max_length=2000)),
                ('imdb', models.CharField(max_length=2000)),
                ('href', models.CharField(max_length=2000)),
                ('desc', models.CharField(max_length=2000)),
                ('genres', models.CharField(max_length=2000)),
                ('casts', models.CharField(max_length=2000)),
                ('countries', models.CharField(max_length=2000)),
                ('production', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=2000)),
                ('year', models.CharField(max_length=2000)),
                ('length', models.CharField(max_length=2000)),
                ('imdb', models.CharField(max_length=2000)),
                ('href', models.CharField(max_length=2000)),
                ('desc', models.CharField(max_length=2000)),
                ('genres', models.CharField(max_length=2000)),
                ('casts', models.CharField(max_length=2000)),
                ('countries', models.CharField(max_length=2000)),
                ('production', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('countLike', models.IntegerField(default=0)),
                ('countComment', models.IntegerField(default=0)),
                ('countWishlist', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='null', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
