# Generated by Django 4.2.2 on 2023-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=2000)),
                ('year', models.CharField(max_length=2000)),
                ('length', models.CharField(max_length=2000)),
                ('imdb', models.CharField(max_length=2000)),
                ('href', models.CharField(max_length=2000)),
                ('desc', models.CharField(max_length=2000)),
                ('genres', models.CharField(max_length=2000)),
                ('casts', models.CharField(max_length=2000)),
                ('countries', models.CharField(max_length=2000)),
                ('production', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserSub',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
